import kagglehub
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import helper.model_trainer as model_trainer
import torch

features = ['underlying', 'X0','X1','X2','X3','X4','X5','X6','X7','X8','X9','X10','X11','X12','X13','X14','X15','X16','X17','X18','X19','X20','X21','X22','X23','X24','X25','X26','X27','X28','X29','X30','X31','X32','X33','X34','X35','X36','X37','X38','X39','X40','X41']

def plot_train_nifty(train_df):
    train_df.plot(x="timestamp", y='underlying', kind='line')
    plt.show()

def plot_train_calls(train_df):
    train_df.plot(x="timestamp", y='call_iv_23500', kind='line')
    train_df.plot(x="timestamp", y='call_iv_23600', kind='line')
    train_df.plot(x="timestamp", y='call_iv_23700', kind='line')
    train_df.plot(x="timestamp", y='call_iv_23800', kind='line')
    train_df.plot(x="timestamp", y='call_iv_23900', kind='line')
    train_df.plot(x="timestamp", y='call_iv_24000', kind='line')
    train_df.plot(x="timestamp", y='call_iv_24100', kind='line')
    train_df.plot(x="timestamp", y='call_iv_24200', kind='line')
    train_df.plot(x="timestamp", y='call_iv_24300', kind='line')
    train_df.plot(x="timestamp", y='call_iv_24400', kind='line')
    train_df.plot(x="timestamp", y='call_iv_24500', kind='line')
    train_df.plot(x="timestamp", y='call_iv_24600', kind='line')
    train_df.plot(x="timestamp", y='call_iv_24700', kind='line')
    train_df.plot(x="timestamp", y='call_iv_24800', kind='line')
    train_df.plot(x="timestamp", y='call_iv_24900', kind='line')
    train_df.plot(x="timestamp", y='call_iv_25000', kind='line')
    train_df.plot(x="timestamp", y='call_iv_25100', kind='line')
    train_df.plot(x="timestamp", y='call_iv_25200', kind='line')
    train_df.plot(x="timestamp", y='call_iv_25300', kind='line')
    train_df.plot(x="timestamp", y='call_iv_25400', kind='line')
    train_df.plot(x="timestamp", y='call_iv_25500', kind='line')
    train_df.plot(x="timestamp", y='call_iv_25600', kind='line')
    train_df.plot(x="timestamp", y='call_iv_25700', kind='line')
    train_df.plot(x="timestamp", y='call_iv_25800', kind='line')
    train_df.plot(x="timestamp", y='call_iv_25900', kind='line')
    train_df.plot(x="timestamp", y='call_iv_26000', kind='line')
    plt.show()

def plot_train_puts(train_df):
    train_df.plot(x="timestamp", y='put_iv_22500', kind='line')
    train_df.plot(x="timestamp", y='put_iv_22600', kind='line')
    train_df.plot(x="timestamp", y='put_iv_22700', kind='line')
    train_df.plot(x="timestamp", y='put_iv_22800', kind='line')
    train_df.plot(x="timestamp", y='put_iv_22900', kind='line')
    train_df.plot(x="timestamp", y='put_iv_23000', kind='line')
    train_df.plot(x="timestamp", y='put_iv_23100', kind='line')
    train_df.plot(x="timestamp", y='put_iv_23200', kind='line')
    train_df.plot(x="timestamp", y='put_iv_23300', kind='line')
    train_df.plot(x="timestamp", y='put_iv_23400', kind='line')
    train_df.plot(x="timestamp", y='put_iv_23500', kind='line')
    train_df.plot(x="timestamp", y='put_iv_23600', kind='line')
    train_df.plot(x="timestamp", y='put_iv_23700', kind='line')
    train_df.plot(x="timestamp", y='put_iv_23800', kind='line')
    train_df.plot(x="timestamp", y='put_iv_23900', kind='line')
    train_df.plot(x="timestamp", y='put_iv_24000', kind='line')
    train_df.plot(x="timestamp", y='put_iv_24100', kind='line')
    train_df.plot(x="timestamp", y='put_iv_24200', kind='line')
    train_df.plot(x="timestamp", y='put_iv_24300', kind='line')
    train_df.plot(x="timestamp", y='put_iv_24400', kind='line')
    train_df.plot(x="timestamp", y='put_iv_24500', kind='line')
    train_df.plot(x="timestamp", y='put_iv_24600', kind='line')
    train_df.plot(x="timestamp", y='put_iv_24700', kind='line')
    train_df.plot(x="timestamp", y='put_iv_24800', kind='line')
    train_df.plot(x="timestamp", y='put_iv_24900', kind='line')
    train_df.plot(x="timestamp", y='put_iv_25000', kind='line')
    plt.show()

def plot_train_params(train_df):
    train_df.plot(x="timestamp", y='X0', kind='line')
    train_df.plot(x="timestamp", y='X1', kind='line')
    train_df.plot(x="timestamp", y='X2', kind='line')
    train_df.plot(x="timestamp", y='X3', kind='line')
    train_df.plot(x="timestamp", y='X4', kind='line')
    train_df.plot(x="timestamp", y='X5', kind='line')
    train_df.plot(x="timestamp", y='X6', kind='line')
    train_df.plot(x="timestamp", y='X7', kind='line')
    train_df.plot(x="timestamp", y='X8', kind='line')
    train_df.plot(x="timestamp", y='X9', kind='line')
    train_df.plot(x="timestamp", y='X10', kind='line')
    train_df.plot(x="timestamp", y='X11', kind='line')
    train_df.plot(x="timestamp", y='X12', kind='line')
    train_df.plot(x="timestamp", y='X13', kind='line')
    train_df.plot(x="timestamp", y='X14', kind='line')
    train_df.plot(x="timestamp", y='X15', kind='line')
    train_df.plot(x="timestamp", y='X16', kind='line')
    train_df.plot(x="timestamp", y='X17', kind='line')
    train_df.plot(x="timestamp", y='X18', kind='line')
    train_df.plot(x="timestamp", y='X19', kind='line')
    train_df.plot(x="timestamp", y='X20', kind='line')
    train_df.plot(x="timestamp", y='X21', kind='line')
    train_df.plot(x="timestamp", y='X22', kind='line')
    train_df.plot(x="timestamp", y='X23', kind='line')
    train_df.plot(x="timestamp", y='X24', kind='line')
    train_df.plot(x="timestamp", y='X25', kind='line')
    train_df.plot(x="timestamp", y='X26', kind='line')
    train_df.plot(x="timestamp", y='X27', kind='line')
    train_df.plot(x="timestamp", y='X28', kind='line')
    train_df.plot(x="timestamp", y='X29', kind='line')
    train_df.plot(x="timestamp", y='X30', kind='line')
    train_df.plot(x="timestamp", y='X31', kind='line')
    train_df.plot(x="timestamp", y='X32', kind='line')
    train_df.plot(x="timestamp", y='X33', kind='line')
    train_df.plot(x="timestamp", y='X34', kind='line')
    train_df.plot(x="timestamp", y='X35', kind='line')
    train_df.plot(x="timestamp", y='X36', kind='line')
    train_df.plot(x="timestamp", y='X37', kind='line')
    train_df.plot(x="timestamp", y='X38', kind='line')
    train_df.plot(x="timestamp", y='X39', kind='line')
    train_df.plot(x="timestamp", y='X40', kind='line')
    train_df.plot(x="timestamp", y='X41', kind='line')
    plt.show()

def plot_test_one_call(test_df, train_df):
    
    X = train_df[features].values
    X_tensor = torch.tensor(X, dtype=torch.float32)
    loaded_model = model_trainer.Net()
    loaded_model.load_state_dict(torch.load('models/01_test.pth'))

    out = loaded_model(X_tensor)
    print(out)
    # for element in test_df:
    #     print(element)
    # train_df.plot(x="timestamp", y='call_iv_24000', kind='scatter')
    # plt.show()

